#include <DetoursPatch.h>
#include <chrono>
#include <thread>

#include <GAME/Game.h>
#include <D2Skills.h>

#include "ESEDamageCalc.h"
#include "D2Game/UNIT/SUnitDmg_ESE_INTERCEPTS.h"
#include "D2Game/UNIT/SUnitEvent_ESE_Intercepts.h"
#include "D2Game/UNIT/SUnit_ESE_Intercepts.h"
#include "D2Game/OBJECTS/ObjEval_ESE_Intercepts.h"
#include "D2Game/SKILLS/SkillAma_ESE_Intercepts.h"
#include "D2Game/SKILLS/SkillAss_ESE_Intercepts.h"
#include "D2Game/SKILLS/SkillBar_ESE_Intercepts.h"
#include "D2Game/SKILLS/SkillDruid_ESE_Intercepts.h"
#include "D2Game/SKILLS/SkillItem_ESE_Intercepts.h"
#include "D2Game/SKILLS/SkillMonst_ESE_Intercepts.h"
#include "D2Game/SKILLS/SkillNec_ESE_Intercepts.h"
#include "D2Game/SKILLS/SkillPal_ESE_Intercepts.h"
#include "D2Game/SKILLS/Skills_ESE_Intercepts.h"
#include "D2Game/SKILLS/SkillSor_ESE_Intercepts.h"
#include "D2Game/MISSILES/MissMode_ESE_Intercepts.h"
#include "D2Game/MONSTER/MonsterMode_ESE_Intercepts.h"
#include "D2Game/MONSTER/MonsterUnique_ESE_Intercepts.h"

#if defined(__clang__)
#pragma clang diagnostic ignored "-Wmicrosoft-cast"
#endif

extern "C"
{
    __declspec(dllexport) constexpr int __cdecl GetBaseOrdinal() { return 0; }
    __declspec(dllexport) constexpr int __cdecl GetLastOrdinal() { return -1; }
    constexpr int GetOrdinalCount() { return GetLastOrdinal() - GetBaseOrdinal() + 1; }

    __declspec(dllexport) PatchAction __cdecl GetPatchAction(int ordinal)
    {
        return PatchAction::Ignore;
    }

    static const int D2GameImageBase = 0x6FC30000;
    static const int D2CommonImageBase = 0x6FD40000;

    // TODO: AIBAAL_GetTargetScore uses some sort of damage in score calcualtion
    // TODO: AITHINK_GetTargetScore uses some sort of damage in score calcualtion
    static ExtraPatchAction extraPatchActions[] =
    {
       // SUnitEvent
       {0x6FCC3610 - D2GameImageBase, &ESE_INTERCEPT_SUNITEVENT_FreeTimerList, PatchAction::FunctionReplaceOriginalByPatch, &SUNITEVENT_FreeTimerList_Original},
       {0x6FCC3650 - D2GameImageBase, &ESE_INTERCEPT_SUNITEVENT_AllocTimer, PatchAction::FunctionReplaceOriginalByPatch, &SUNITEVENT_AllocTimer_Original},
       {0x6FCC36D0 - D2GameImageBase, &ESE_INTERCEPT_SUNITEVENT_FreeTimer, PatchAction::FunctionReplaceOriginalByPatch, &SUNITEVENT_FreeTimer_Original},
       {0x6FCC3750 - D2GameImageBase, &ESE_INTERCEPT_SUNITEVENT_GetTimer, PatchAction::FunctionReplaceOriginalByPatch, &SUNITEVENT_GetTimer_Original},
       {0x6FCC3790 - D2GameImageBase, &ESE_INTERCEPT_SUNITEVENT_EventFunc_Handler, PatchAction::FunctionReplaceOriginalByPatch, &SUNITEVENT_EventFunc_Handler_Original},
       
       // SUnit
       {0x6FCBDE90 - D2GameImageBase, &ESE_INTERCEPT_sub_6FCBDE90, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FCBDE90_Original},
       
       // SkillAma
       {0x6FCF30D0 - D2GameImageBase, &ESE_INTERCEPT_D2Game_10049_Return1, PatchAction::FunctionReplaceOriginalByPatch, &D2Game_10049_Return1_Original},
       {0x6FCF30E0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt04_Arrow_Bolt, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt04_Arrow_Bolt_Original},
       {0x6FCF3120 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt05_Jab, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt05_Jab_Original},
       {0x6FCF3170 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt06_PowerStrike_ChargedStrike, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt06_PowerStrike_ChargedStrike_Original},
       {0x6FCF3280 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt07_Impale, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt07_Impale_Original},
       {0x6FCF3510 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt08_Strafe, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt08_Strafe_Original},
       {0x6FCF3690 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt09_Fend, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt09_Fend_Original},
       {0x6FCF37B0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt37_Zeal_Fury_BloodLordFrenzy, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt37_Zeal_Fury_BloodLordFrenzy_Original},
       {0x6FCF38C0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt10_LightningStrike, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt10_LightningStrike_Original},
       {0x6FCF3A70 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo006_InnerSight_SlowMissiles, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo006_InnerSight_SlowMissiles_Original},
       {0x6FCF3B90 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_AuraCallback_InnerSight_SlowMissiles, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_AuraCallback_InnerSight_SlowMissiles_Original},
       {0x6FCF3C00 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo007_Jab, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo007_Jab_Original},
       {0x6FCF3D70 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo008_MultipleShot_Teeth_ShockWave, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo008_MultipleShot_Teeth_ShockWave_Original},
       {0x6FCF4080 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo010_GuidedArrow_BoneSpirit, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo010_GuidedArrow_BoneSpirit_Original},
       {0x6FCF4280 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_AddDamagePercentBonus, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_AddDamagePercentBonus_Original},
       {0x6FCF42B0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo011_ChargedStrike, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo011_ChargedStrike_Original},
       {0x6FCF44D0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo012_Strafe, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo012_Strafe_Original},
       {0x6FCF47D0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo013_Fend_Zeal_Fury, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo013_Fend_Zeal_Fury_Original},
       {0x6FCF4A20 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo014_LightningStrike, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo014_LightningStrike_Original},
       {0x6FCF4C50 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo015_Dopplezon, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo015_Dopplezon_Original},
       {0x6FCF4EE0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo016_Valkyrie, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo016_Valkyrie_Original},
        
        // SkillAss
        {0x6FCF5090 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt22_PsychicHammer, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt22_PsychicHammer_Original},
        {0x6FCF50E0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo033_PsychicHammer, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo033_PsychicHammer_Original},
        {0x6FCF52C0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt23_AssasinChargeStrikes, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt23_AssasinChargeStrikes_Original},
        {0x6FCF52E0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_StatRemoveCallback_ProgressiveStrike, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_StatRemoveCallback_ProgressiveStrike_Original},
        {0x6FCF52F0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo034_TigerStrike_CobraStrike_RoyalStrike, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo034_TigerStrike_CobraStrike_RoyalStrike_Original},
        {0x6FCF55B0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo035_FistsOfFire_ClawsOfThunder_BladesOfIce, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo035_FistsOfFire_ClawsOfThunder_BladesOfIce_Original},
        {0x6FCF5680 - D2GameImageBase, &ESE_INTERCEPT_sub_6FCF5680, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FCF5680_Original},
        {0x6FCF5870 - D2GameImageBase, &ESE_INTERCEPT_sub_6FCF5870, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FCF5870_Original},
        {0x6FCF5B90 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_GetSkillsTxtRecord, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_GetSkillsTxtRecord_Original},
        {0x6FCF5BC0 - D2GameImageBase, &ESE_INTERCEPT_sub_6FCF5BC0, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FCF5BC0_Original},
        {0x6FCF5DE0 - D2GameImageBase, &ESE_INTERCEPT_sub_6FCF5DE0, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FCF5DE0_Original},
        {0x6FCF5E20 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_GetProgressiveSkillMissileId, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_GetProgressiveSkillMissileId_Original},
        {0x6FCF5EE0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_EvaluateProgressiveSkillCalc, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_EvaluateProgressiveSkillCalc_Original},
        {0x6FCF6000 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo038_FistsOfFire_BladesOfIce_ProgressiveFn2, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo038_FistsOfFire_BladesOfIce_ProgressiveFn2_Original},
        {0x6FCF6140 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo039_FistsOfFire_BladesOfIce_ProgressiveFn3, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo039_FistsOfFire_BladesOfIce_ProgressiveFn3_Original},
        {0x6FCF6420 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo036_ClawsOfThunder_ProgressiveFn2, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo036_ClawsOfThunder_ProgressiveFn2_Original},
        {0x6FCF6500 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo037_ClawsOfThunder_ProgressiveFn3, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo037_ClawsOfThunder_ProgressiveFn3_Original},
        {0x6FCF6600 - D2GameImageBase, &ESE_INTERCEPT_sub_6FCF6600, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FCF6600_Original},
        {0x6FCF6C10 - D2GameImageBase, &ESE_INTERCEPT_sub_6FCF6C10, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FCF6C10_Original},
        {0x6FCF6C70 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo143_FistsOfFire_RoyalStrike_ProgressiveFn, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo143_FistsOfFire_RoyalStrike_ProgressiveFn_Original},
        {0x6FCF6D70 - D2GameImageBase, &ESE_INTERCEPT_sub_6FCF6D70, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FCF6D70_Original},
        {0x6FCF7390 - D2GameImageBase, &ESE_INTERCEPT_sub_6FCF7390, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FCF7390_Original},
        {0x6FCF7590 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo040_RoyalStrike_ProgressiveFn1, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo040_RoyalStrike_ProgressiveFn1_Original},
        {0x6FCF7610 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo041_RoyalStrike_ProgressiveFn3, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo041_RoyalStrike_ProgressiveFn3_Original},
        {0x6FCF77E0 - D2GameImageBase, &ESE_INTERCEPT_sub_6FCF77E0, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FCF77E0_Original},
        {0x6FCF7AD0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt24_DragonTalon, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt24_DragonTalon_Original},
        {0x6FCF7BC0 - D2GameImageBase, &ESE_INTERCEPT_sub_6FCF7BC0, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FCF7BC0_Original},
        {0x6FCF7CE0 - D2GameImageBase, &ESE_INTERCEPT_sub_6FCF7CE0, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FCF7CE0_Original},
        {0x6FCF8110 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo042_DragonTalon, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo042_DragonTalon_Original},
        {0x6FCF8330 - D2GameImageBase, &ESE_INTERCEPT_sub_6FCF8330, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FCF8330_Original},
        {0x6FCF8550 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo043_ShockField, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo043_ShockField_Original},
        {0x6FCF8610 - D2GameImageBase, &ESE_INTERCEPT_sub_6FCF8610, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FCF8610_Original},
        {0x6FCF88E0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo044_BladeSentinel, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo044_BladeSentinel_Original},
        {0x6FCF8B00 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo045_Sentry, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo045_Sentry_Original},
        {0x6FCF8BA0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo046_DragonClaw, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo046_DragonClaw_Original},
        {0x6FCF8C70 - D2GameImageBase, &ESE_INTERCEPT_sub_6FCF8C70, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FCF8C70_Original},
        {0x6FCF8DD0 - D2GameImageBase, &ESE_INTERCEPT_sub_6FCF8DD0, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FCF8DD0_Original},
        {0x6FCF8ED0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo047_CloakOfShadows, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo047_CloakOfShadows_Original},
        {0x6FCF9160 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_AuraCallback_CloakOfShadows, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_AuraCallback_CloakOfShadows_Original},
        {0x6FCF9260 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo048_BladeFury, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo048_BladeFury_Original},
        {0x6FCF93B0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt26_BladeFury, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt26_BladeFury_Original},
        {0x6FCF9550 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_StatRemoveCallback_RemoveState, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_StatRemoveCallback_RemoveState_Original},
        {0x6FCF9580 - D2GameImageBase, &ESE_INTERCEPT_sub_6FCF9580, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FCF9580_Original},
        {0x6FCF9750 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo049_ShadowWarrior_Master, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo049_ShadowWarrior_Master_Original},
        {0x6FCF9B50 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt27_DragonTail, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt27_DragonTail_Original},
        {0x6FCF9C70 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo050_DragonTail, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo050_DragonTail_Original},
        {0x6FCF9EA0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_StatRemoveCallback_MindBlast, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_StatRemoveCallback_MindBlast_Original},
        {0x6FCF9FF0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_AuraCallback_MindBlast, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_AuraCallback_MindBlast_Original},
        {0x6FCFA350 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo051_MindBlast, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo051_MindBlast_Original},
        {0x6FCFA4F0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo052_DragonFlight, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo052_DragonFlight_Original},
        {0x6FCFA720 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt28_BladeShield, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt28_BladeShield_Original},
        {0x6FCFA880 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo053_Unused, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo053_Unused_Original},
        {0x6FCFA980 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_AuraCallback_SrvDo142, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_AuraCallback_SrvDo142_Original},
        {0x6FCFAA20 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo142_Unused, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo142_Unused_Original},
        {0x6FCFAB60 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo054_BladeShield, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo054_BladeShield_Original},
        
        // SkillBar
        {0x6FCFABF0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt32_Conversion_Bash_Stun_Concentrate_BearSmite, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt32_Conversion_Bash_Stun_Concentrate_BearSmite_Original},
        {0x6FCFAE50 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt33_FindPotion_GrimWard, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt33_FindPotion_GrimWard_Original},
        {0x6FCFAE90 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo069_FindPotion, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo069_FindPotion_Original},
        {0x6FCFB070 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_ApplyWarcryStats, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_ApplyWarcryStats_Original},
        {0x6FCFB1D0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo068_BasicShout, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo068_BasicShout_Original},
        {0x6FCFB270 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo070_DoubleSwing, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo070_DoubleSwing_Original},
        {0x6FCFB320 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_Callback_FindTargetForTaunt, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_Callback_FindTargetForTaunt_Original},
        {0x6FCFB390 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo071_Taunt, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo071_Taunt_Original},
        {0x6FCFB610 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt34_FindItem, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt34_FindItem_Original},
        {0x6FCFB630 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo072_FindItem, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo072_FindItem_Original},
        {0x6FCFB7A0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo074_DoubleThrow, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo074_DoubleThrow_Original},
        {0x6FCFB8A0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo075_GrimWard, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo075_GrimWard_Original},
        {0x6FCFBB40 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_RollFrenzyDamage, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_RollFrenzyDamage_Original},
        {0x6FCFBCE0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_ApplyFrenzyStats, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_ApplyFrenzyStats_Original},
        {0x6FCFBE80 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo009_Frenzy, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo009_Frenzy_Original},
        {0x6FCFBF80 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_CurseStateCallback_Whirlwind, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_CurseStateCallback_Whirlwind_Original},
        {0x6FCFBFE0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt38_Whirlwind, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt38_Whirlwind_Original},
        {0x6FCFC3A0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_RemoveWhirlwindStats, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_RemoveWhirlwindStats_Original},
        {0x6FCFC4C0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo076_Whirlwind, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo076_Whirlwind_Original},
        {0x6FCFC8E0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt39_Berserk, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt39_Berserk_Original},
        {0x6FCFCB30 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt40_Leap, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt40_Leap_Original},
        {0x6FCFCF60 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_FindLeapTargetPosition, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_FindLeapTargetPosition_Original},
        {0x6FCFD280 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo077_Leap, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo077_Leap_Original},
        {0x6FCFD3C0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SetVelocityForLeap, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SetVelocityForLeap_Original},
        {0x6FCFD4C0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_Leap, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_Leap_Original},
        {0x6FCFD880 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt41_LeapAttack, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt41_LeapAttack_Original},
        {0x6FCFD9B0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo078_LeapAttack, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo078_LeapAttack_Original},
        {0x6FCFDC40 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_FindLeapAttackTarget, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_FindLeapAttackTarget_Original},
        
        // SkillDruid
        {0x6FCFDCF0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo114_Raven, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo114_Raven_Original},
        {0x6FCFDE90 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo115_Vines, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo115_Vines_Original},
        {0x6FCFE030 - D2GameImageBase, &ESE_INTERCEPT_sub_6FCFE030, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FCFE030_Original},
        {0x6FCFE0E0 - D2GameImageBase, &ESE_INTERCEPT_sub_6FCFE0E0, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FCFE0E0_Original},
        {0x6FCFE200 - D2GameImageBase, &ESE_INTERCEPT_sub_6FCFE200, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FCFE200_Original},
        {0x6FCFE330 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo116_Wearwolf_Wearbear, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo116_Wearwolf_Wearbear_Original},
        {0x6FCFE4C0 - D2GameImageBase, &ESE_INTERCEPT_sub_6FCFE4C0, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FCFE4C0_Original},
        {0x6FCFE5F0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo117_Firestorm, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo117_Firestorm_Original},
        {0x6FCFE6A0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo118_Twister_Tornado, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo118_Twister_Tornado_Original},
        {0x6FCFE750 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo119_DruidSummon, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo119_DruidSummon_Original},
        {0x6FCFE900 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt56_FeralRage_Maul, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt56_FeralRage_Maul_Original},
        {0x6FCFEA60 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo120_FeralRage_Maul, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo120_FeralRage_Maul_Original},
        {0x6FCFEC90 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt57_Rabies, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt57_Rabies_Original},
        {0x6FCFEDD0 - D2GameImageBase, &ESE_INTERCEPT_sub_6FCFEDD0, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FCFEDD0_Original},
        {0x6FCFEFD0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo121_Rabies, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo121_Rabies_Original},
        {0x6FCFF2E0 - D2GameImageBase, &ESE_INTERCEPT_sub_6FCFF2E0, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FCFF2E0_Original},
        {0x6FCFF3C0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt58_FireClaws, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt58_FireClaws_Original},
        {0x6FCFF4E0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo122_Hunger, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo122_Hunger_Original},
        {0x6FCFF710 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo123_Volcano, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo123_Volcano_Original},
        {0x6FCFF870 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo124_Armageddon_Hurricane, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo124_Armageddon_Hurricane_Original},
        {0x6FCFFAB0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo145_Unused, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo145_Unused_Original},
        {0x6FCFFCA0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo146_Unused, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo146_Unused_Original},
        {0x6FD00140 - D2GameImageBase, &ESE_INTERCEPT_D2GAME_EventFunc25_6FD00140, PatchAction::FunctionReplaceOriginalByPatch, &D2GAME_EventFunc25_6FD00140_Original},
        {0x6FD00370 - D2GameImageBase, &ESE_INTERCEPT_sub_6FD00370, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FD00370_Original},
        {0x6FD004E0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo125_WakeOfDestruction, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo125_WakeOfDestruction_Original},
        {0x6FD00660 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt59_ImpInferno, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt59_ImpInferno_Original},
        {0x6FD00710 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo126_ImpInferno, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo126_ImpInferno_Original},
        {0x6FD009F0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt60_SuckBlood, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt60_SuckBlood_Original},
        {0x6FD00BE0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo127_SuckBlood, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo127_SuckBlood_Original},
        {0x6FD00DC0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo128_CryHelp, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo128_CryHelp_Original},
        {0x6FD00EC0 - D2GameImageBase, &ESE_INTERCEPT_sub_6FD00EC0, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FD00EC0_Original},
        {0x6FD01010 - D2GameImageBase, &ESE_INTERCEPT_sub_6FD01010, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FD01010_Original},
        {0x6FD01170 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo129_ImpTeleport, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo129_ImpTeleport_Original},
        {0x6FD01320 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt61_SelfResurrect, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt61_SelfResurrect_Original},
        {0x6FD01360 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo130_VineAttack, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo130_VineAttack_Original},
        {0x6FD014A0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo131_OverseerWhip, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo131_OverseerWhip_Original},
        {0x6FD017F0 - D2GameImageBase, &ESE_INTERCEPT_sub_6FD017F0, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FD017F0_Original},
        {0x6FD01860 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo132_ImpFireMissile, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo132_ImpFireMissile_Original},
        {0x6FD01910 - D2GameImageBase, &ESE_INTERCEPT_sub_6FD01910, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FD01910_Original},
        {0x6FD019B0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo133_Impregnate, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo133_Impregnate_Original},
        {0x6FD01B00 - D2GameImageBase, &ESE_INTERCEPT_sub_6FD01B00, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FD01B00_Original},
        {0x6FD01BB0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo134_SiegeBeastStomp, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo134_SiegeBeastStomp_Original},
        {0x6FD01CC0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt62_MinionSpawner, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt62_MinionSpawner_Original},
        {0x6FD01D40 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo135_MinionSpawner, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo135_MinionSpawner_Original},
        {0x6FD01F10 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo136_DeathMaul, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo136_DeathMaul_Original},
        {0x6FD02070 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo137_FenrisRage, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo137_FenrisRage_Original},
        {0x6FD02140 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo138_Unused, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo138_Unused_Original},
        {0x6FD02360 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo139_BaalColdMissiles, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo139_BaalColdMissiles_Original},
        {0x6FD024A0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt63_Corpse_VineCycler, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt63_Corpse_VineCycler_Original},
        {0x6FD025C0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo147_Unused, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo147_Unused_Original},
        {0x6FD025E0 - D2GameImageBase, &ESE_INTERCEPT_D2GAME_SKILLS_BloodMana_6FD025E0, PatchAction::FunctionReplaceOriginalByPatch, &D2GAME_SKILLS_BloodMana_6FD025E0_Original},
        {0x6FD026B0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo140_BaalTentacle, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo140_BaalTentacle_Original},
        {0x6FD02950 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo141_BaalCorpseExplode, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo141_BaalCorpseExplode_Original},
        {0x6FD02A50 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_AreaEffect_BaalCorpseExplode, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_AreaEffect_BaalCorpseExplode_Original},
        {0x6FD02A80 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_FindUseableCorpse, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_FindUseableCorpse_Original},
        
        // SkillItem
        {0x6FD02BA0 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_pSpell01_Initializer, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_pSpell01_Initializer_Original},
        {0x6FD02BF0 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_pSpell01_IdentifyItem, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_pSpell01_IdentifyItem_Original},
        {0x6FD02C80 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_pSpell02_CastPortal, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_pSpell02_CastPortal_Original},
        {0x6FD02E10 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_pSpell03_Potion, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_pSpell03_Potion_Original},
        {0x6FD032D0 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_pSpell04_Unused, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_pSpell04_Unused_Original},
        {0x6FD03610 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_pSpell05_RejuvPotion, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_pSpell05_RejuvPotion_Original},
        {0x6FD039A0 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_pSpell09_StaminaPotion, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_pSpell09_StaminaPotion_Original},
        {0x6FD03BB0 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_pSpell09_AntidoteThawingPotion, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_pSpell09_AntidoteThawingPotion_Original},
        {0x6FD03C80 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_pSpell08_ExperienceElixir, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_pSpell08_ExperienceElixir_Original},
        {0x6FD03CD0 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_pSpell07_OpenCube, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_pSpell07_OpenCube_Original},
        {0x6FD03D80 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_pSpell10_CastFireBallOnTarget, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_pSpell10_CastFireBallOnTarget_Original},
        {0x6FD03DF0 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_pSpell11_CastFireBallToCoordinates, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_pSpell11_CastFireBallToCoordinates_Original},
        {0x6FD03E40 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_pSpell_Handler, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_pSpell_Handler_Original},
        {0x6FD040B0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo113_Scroll_Book, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo113_Scroll_Book_Original},
        {0x6FD04270 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_ActivateAura, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_ActivateAura_Original},
        {0x6FD04340 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_DeactivateAura, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_DeactivateAura_Original},
        {0x6FD043F0 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_EventFunc06_AttackerTakesDamage, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_EventFunc06_AttackerTakesDamage_Original},
        {0x6FD044B0 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_EventFunc10_AttackerTakesLightDamage, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_EventFunc10_AttackerTakesLightDamage_Original},
        {0x6FD04570 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_EventFunc11_ApplyFireDamage, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_EventFunc11_ApplyFireDamage_Original},
        {0x6FD04630 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_EventFunc12_ApplyColdDamage, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_EventFunc12_ApplyColdDamage_Original},
        {0x6FD04720 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_EventFunc07_Knockback, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_EventFunc07_Knockback_Original},
        {0x6FD04820 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_EventFunc08_Howl, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_EventFunc08_Howl_Original},
        {0x6FD048B0 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_EventFunc09_Stupidity, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_EventFunc09_Stupidity_Original},
        {0x6FD049D0 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_EventFunc13_DamageToMana, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_EventFunc13_DamageToMana_Original},
        {0x6FD04B10 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_EventFunc14_Freeze, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_EventFunc14_Freeze_Original},
        {0x6FD04C40 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_CalculateOpenWoundsHpRegen, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_CalculateOpenWoundsHpRegen_Original},
        {0x6FD04CF0 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_EventFunc15_OpenWounds, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_EventFunc15_OpenWounds_Original},
        {0x6FD04E50 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_EventFunc16_CrushingBlow, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_EventFunc16_CrushingBlow_Original},
        {0x6FD050D0 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_EventFunc17_ManaAfterKill, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_EventFunc17_ManaAfterKill_Original},
        {0x6FD05160 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_EventFunc28_HealAfterKill, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_EventFunc28_HealAfterKill_Original},
        {0x6FD051E0 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_EventFunc18_HealAfterDemonKill, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_EventFunc18_HealAfterDemonKill_Original},
        {0x6FD05270 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_EventFunc19_Slow, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_EventFunc19_Slow_Original},
        {0x6FD053D0 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_EventFunc20_SkillOnAttackHitKill, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_EventFunc20_SkillOnAttackHitKill_Original},
        {0x6FD05520 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_EventFunc21_SkillOnGetHit, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_EventFunc21_SkillOnGetHit_Original},
        {0x6FD05640 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_EventFunc30_SkillOnDeathLevelup, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_EventFunc30_SkillOnDeathLevelup_Original},
        {0x6FD05750 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_EventFunc29_RestInPeace, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_EventFunc29_RestInPeace_Original},
        {0x6FD05780 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_TimerCallback_ReanimateMonster, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_TimerCallback_ReanimateMonster_Original},
        {0x6FD05B60 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_EventFunc31_Reanimate, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_EventFunc31_Reanimate_Original},
        {0x6FD05C20 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_FindTargetPosition, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_FindTargetPosition_Original},
        {0x6FD05D70 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_HandleItemEffectSkill, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_HandleItemEffectSkill_Original},
        {0x6FD06020 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_CastSkillOnTarget, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_CastSkillOnTarget_Original},
        {0x6FD060F0 - D2GameImageBase, &ESE_INTERCEPT_SKILLITEM_CastSkillOnPosition, PatchAction::FunctionReplaceOriginalByPatch, &SKILLITEM_CastSkillOnPosition_Original},
        
        // SkillMonst
        {0x6FD061C0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt42_FireHit, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt42_FireHit_Original},
        {0x6FD062E0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo083_FireHit, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo083_FireHit_Original},
        {0x6FD06330 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt43_MaggotEgg, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt43_MaggotEgg_Original},
        {0x6FD06360 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo084_MaggotEgg, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo084_MaggotEgg_Original},
        {0x6FD064D0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo085_UnholyBolt_ShamanFire, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo085_UnholyBolt_ShamanFire_Original},
        {0x6FD06590 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt44_MaggotUp, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt44_MaggotUp_Original},
        {0x6FD066A0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt45_MaggotDown, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt45_MaggotDown_Original},
        {0x6FD06730 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo086_MaggotDown, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo086_MaggotDown_Original},
        {0x6FD06880 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo087_MaggotLay, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo087_MaggotLay_Original},
        {0x6FD06A60 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt46_AndrialSpray, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt46_AndrialSpray_Original},
        {0x6FD06B20 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo088_AndrialSpray, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo088_AndrialSpray_Original},
        {0x6FD06D60 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt47_Jump, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt47_Jump_Original},
        {0x6FD070F0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo089_Jump, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo089_Jump_Original},
        {0x6FD074B0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt48_SwarmMove, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt48_SwarmMove_Original},
        {0x6FD07540 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo090_SwarmMove, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo090_SwarmMove_Original},
        {0x6FD075E0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt49_Nest_EvilHutSpawner, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt49_Nest_EvilHutSpawner_Original},
        {0x6FD07770 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo091_Nest_EvilHutSpawner, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo091_Nest_EvilHutSpawner_Original},
        {0x6FD07920 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt50_QuickStrike, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt50_QuickStrike_Original},
        {0x6FD07970 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo092_QuickStrike, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo092_QuickStrike_Original},
        {0x6FD07A30 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo093_GargoyleTrap, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo093_GargoyleTrap_Original},
        {0x6FD07C50 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt51_Submerge, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt51_Submerge_Original},
        {0x6FD07C70 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo094_Submerge, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo094_Submerge_Original},
        {0x6FD07CB0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt52_Emerge, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt52_Emerge_Original},
        {0x6FD07CD0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt53_MonInferno, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt53_MonInferno_Original},
        {0x6FD07D80 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SetInfernoFrame, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SetInfernoFrame_Original},
        {0x6FD07E30 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo095_MonInferno, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo095_MonInferno_Original},
        {0x6FD081E0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_UpdateInfernoAnimationParameters, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_UpdateInfernoAnimationParameters_Original},
        {0x6FD082D0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo152_DiabLight, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo152_DiabLight_Original},
        {0x6FD08680 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo096_ZakarumHeal_Bestow, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo096_ZakarumHeal_Bestow_Original},
        {0x6FD08850 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_ResurrectUnit, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_ResurrectUnit_Original},
        {0x6FD089E0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo097_Resurrect, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo097_Resurrect_Original},
        {0x6FD08BB0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo098_MonTeleport, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo098_MonTeleport_Original},
        {0x6FD08CD0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo099_PrimePoisonNova, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo099_PrimePoisonNova_Original},
        {0x6FD08EB0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo100_DiabCold, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo100_DiabCold_Original},
        {0x6FD09000 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo101_FingerMageSpider, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo101_FingerMageSpider_Original},
        {0x6FD092B0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo102_DiabWall, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo102_DiabWall_Original},
        {0x6FD09410 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_MissileInit_DiabWall, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_MissileInit_DiabWall_Original},
        {0x6FD094B0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt54_DiabRun, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt54_DiabRun_Original},
        {0x6FD09570 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo103_DiabRun, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo103_DiabRun_Original},
        {0x6FD09890 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo104_DiabPrison, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo104_DiabPrison_Original},
        {0x6FD09970 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo105_DesertTurret, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo105_DesertTurret_Original},
        {0x6FD09BF0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo106_ArcaneTower, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo106_ArcaneTower_Original},
        {0x6FD09C90 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt55_Mosquito, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt55_Mosquito_Original},
        {0x6FD09DE0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo107_Mosquito, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo107_Mosquito_Original},
        {0x6FD0A190 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo108_RegurgitatorEat, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo108_RegurgitatorEat_Original},
        {0x6FD0A340 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_GetMonFrenzySequenceFrame, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_GetMonFrenzySequenceFrame_Original},
        {0x6FD0A3D0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_RollMonFrenzyDamage, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_RollMonFrenzyDamage_Original},
        {0x6FD0A520 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt25_64_DragonClaw_MonFrenzy, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt25_64_DragonClaw_MonFrenzy_Original},
        {0x6FD0A530 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo109_MonFrenzy, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo109_MonFrenzy_Original},
        {0x6FD0A5E0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo148_DoomKnightMissile, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo148_DoomKnightMissile_Original},
        {0x6FD0A720 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo149_NecromageMissile, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo149_NecromageMissile_Original},
        {0x6FD0A860 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo110_Hireable_RogueMissile, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo110_Hireable_RogueMissile_Original},
        {0x6FD0A9B0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo112_MonCurseCast, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo112_MonCurseCast_Original},
        {0x6FD0AC20 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_CreateSpiderLayMissile, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_CreateSpiderLayMissile_Original},
        {0x6FD0AE10 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo111_FetishAura, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo111_FetishAura_Original},
        
        // SkillNec
        {0x6FD0AF30 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt15_RaiseSkeleton_Mage, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt15_RaiseSkeleton_Mage_Original},
        {0x6FD0AF70 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt16_PoisonDagger, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt16_PoisonDagger_Original},
        {0x6FD0B0B0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt17_Poison_CorpseExplosion, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt17_Poison_CorpseExplosion_Original},
        {0x6FD0B0F0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt19_BonePrison, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt19_BonePrison_Original},
        {0x6FD0B120 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt20_IronGolem, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt20_IronGolem_Original},
        {0x6FD0B190 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt21_Revive, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt21_Revive_Original},
        {0x6FD0B250 - D2GameImageBase, &ESE_INTERCEPT_sub_6FD0B250, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FD0B250_Original},
        {0x6FD0B2B0 - D2GameImageBase, &ESE_INTERCEPT_sub_6FD0B2B0, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FD0B2B0_Original},
        {0x6FD0B3D0 - D2GameImageBase, &ESE_INTERCEPT_sub_6FD0B3D0, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FD0B3D0_Original},
        {0x6FD0B450 - D2GameImageBase, &ESE_INTERCEPT_sub_6FD0B450, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FD0B450_Original},
        {0x6FD0B790 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo030_Curse, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo030_Curse_Original},
        {0x6FD0B9F0 - D2GameImageBase, &ESE_INTERCEPT_sub_6FD0B9F0, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FD0B9F0_Original},
        {0x6FD0BB60 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo059_Attract, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo059_Attract_Original},
        {0x6FD0BDA0 - D2GameImageBase, &ESE_INTERCEPT_sub_6FD0BDA0, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FD0BDA0_Original},
        {0x6FD0BE50 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo061_Confuse, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo061_Confuse_Original},
        {0x6FD0C060 - D2GameImageBase, &ESE_INTERCEPT_sub_6FD0C060, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FD0C060_Original},
        {0x6FD0C2B0 - D2GameImageBase, &ESE_INTERCEPT_sub_6FD0C2B0, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FD0C2B0_Original},
        {0x6FD0C2E0 - D2GameImageBase, &ESE_INTERCEPT_D2GAME_SetSummonResistance_6FD0C2E0, PatchAction::FunctionReplaceOriginalByPatch, &D2GAME_SetSummonResistance_6FD0C2E0_Original},
        {0x6FD0C3A0 - D2GameImageBase, &ESE_INTERCEPT_D2GAME_SetUnitComponent_6FD0C3A0, PatchAction::FunctionReplaceOriginalByPatch, &D2GAME_SetUnitComponent_6FD0C3A0_Original},
        {0x6FD0C500 - D2GameImageBase, &ESE_INTERCEPT_sub_6FD0C500, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FD0C500_Original},
        {0x6FD0C530 - D2GameImageBase, &ESE_INTERCEPT_D2GAME_SetSummonPassiveStats_6FD0C530, PatchAction::FunctionReplaceOriginalByPatch, &D2GAME_SetSummonPassiveStats_6FD0C530_Original},
        {0x6FD0CB10 - D2GameImageBase, &ESE_INTERCEPT_D2GAME_SKILLS_SetSummonBaseStats_6FD0CB10, PatchAction::FunctionReplaceOriginalByPatch, &D2GAME_SKILLS_SetSummonBaseStats_6FD0CB10_Original},
        {0x6FD0CC10 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo031_RaiseSkeleton_Mage, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo031_RaiseSkeleton_Mage_Original},
        {0x6FD0CFC0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo032_PoisonDagger, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo032_PoisonDagger_Original},
        {0x6FD0D000 - D2GameImageBase, &ESE_INTERCEPT_sub_6FD0D000, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FD0D000_Original},
        {0x6FD0D0D0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo055_CorpseExplosion, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo055_CorpseExplosion_Original},
        {0x6FD0D620 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo056_Golem, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo056_Golem_Original},
        {0x6FD0D7B0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo057_IronGolem, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo057_IronGolem_Original},
        {0x6FD0DAC0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo058_Revive, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo058_Revive_Original},
        {0x6FD0DF40 - D2GameImageBase, &ESE_INTERCEPT_sub_6FD0DF40, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FD0DF40_Original},
        {0x6FD0E050 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo060_BoneWall, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo060_BoneWall_Original},
        {0x6FD0E4C0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo062_BonePrison, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo062_BonePrison_Original},
        {0x6FD0E790 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo063_PoisonExplosion, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo063_PoisonExplosion_Original},
        {0x6FD0E840 - D2GameImageBase, &ESE_INTERCEPT_D2GAME_EventFunc04_6FD0E840, PatchAction::FunctionReplaceOriginalByPatch, &D2GAME_EventFunc04_6FD0E840_Original},
        {0x6FD0EDE0 - D2GameImageBase, &ESE_INTERCEPT_D2GAME_EventFunc05_6FD0EDE0, PatchAction::FunctionReplaceOriginalByPatch, &D2GAME_EventFunc05_6FD0EDE0_Original},
        {0x6FD0F000 - D2GameImageBase, &ESE_INTERCEPT_D2GAME_EventFunc22_6FD0F000, PatchAction::FunctionReplaceOriginalByPatch, &D2GAME_EventFunc22_6FD0F000_Original},
        {0x6FD0F1F0 - D2GameImageBase, &ESE_INTERCEPT_D2GAME_EventFunc23_6FD0F1F0, PatchAction::FunctionReplaceOriginalByPatch, &D2GAME_EventFunc23_6FD0F1F0_Original},
        {0x6FD0F590 - D2GameImageBase, &ESE_INTERCEPT_sub_6FD0F590, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FD0F590_Original},
        {0x6FD0F5E0 - D2GameImageBase, &ESE_INTERCEPT_D2GAME_EventFunc26_6FD0F5E0, PatchAction::FunctionReplaceOriginalByPatch, &D2GAME_EventFunc26_6FD0F5E0_Original},
        {0x6FD0F7A0 - D2GameImageBase, &ESE_INTERCEPT_D2GAME_EventFunc27_6FD0F7A0, PatchAction::FunctionReplaceOriginalByPatch, &D2GAME_EventFunc27_6FD0F7A0_Original},
        
        // SkillPal
        {0x6FD18330 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt29_Sacrifice, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt29_Sacrifice_Original},
        {0x6FD184B0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo064_Sacrifice, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo064_Sacrifice_Original},
        {0x6FD18650 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo150_Smite, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo150_Smite_Original},
        {0x6FD18900 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo065_BasicAura, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo065_BasicAura_Original},
        {0x6FD18BC0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_AuraCallback_BasicAura, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_AuraCallback_BasicAura_Original},
        {0x6FD18FE0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_CurseStateCallback_BasicAura, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_CurseStateCallback_BasicAura_Original},
        {0x6FD19020 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo066_HolyFire_HolyShock_Sanctuary_Conviction, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo066_HolyFire_HolyShock_Sanctuary_Conviction_Original},
        {0x6FD19390 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_AuraCallback_HolyFire_HolyShock_Sanctuary_Conviction, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_AuraCallback_HolyFire_HolyShock_Sanctuary_Conviction_Original},
        {0x6FD19460 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt31_Charge, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt31_Charge_Original},
        {0x6FD19780 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo067_Charge, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo067_Charge_Original},
        {0x6FD19C80 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt35_Vengeance, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt35_Vengeance_Original},
        {0x6FD1A200 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo073_BlessedHammer, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo073_BlessedHammer_Original},
        {0x6FD1A480 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt36_HolyShield, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt36_HolyShield_Original},
        {0x6FD1A4A0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo079_Conversion, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo079_Conversion_Original},
        {0x6FD1A900 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_StatRemoveCallback_Conversion, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_StatRemoveCallback_Conversion_Original},
        {0x6FD1AA50 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo080_FistOfTheHeavens, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo080_FistOfTheHeavens_Original},
        {0x6FD1ABC0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo081_HolyFreeze, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo081_HolyFreeze_Original},
        {0x6FD1AF40 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_CurseStateCallback_HolyFreeze, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_CurseStateCallback_HolyFreeze_Original},
        {0x6FD1AF90 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_AuraCallback_HolyFreeze, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_AuraCallback_HolyFreeze_Original},
        {0x6FD1B100 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_ApplyRedemptionEffect, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_ApplyRedemptionEffect_Original},
        {0x6FD1B260 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo082_Redemption, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo082_Redemption_Original},
        {0x6FD1B490 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_AuraCallback_Redemption, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_AuraCallback_Redemption_Original},
        {0x6FD1B4C0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_ApplyThornsDamage, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_ApplyThornsDamage_Original},
        
        // Skills
        {0x6FD0F8B0 - D2GameImageBase, &ESE_INTERCEPT_sub_6FD0F8B0, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FD0F8B0_Original},
        {0x6FD0FA00 - D2GameImageBase, &ESE_INTERCEPT_sub_6FD0FA00, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FD0FA00_Original},
        {0x6FD0FDD0 - D2GameImageBase, &ESE_INTERCEPT_sub_6FD0FDD0, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FD0FDD0_Original},
        {0x6FD0FE50 - D2GameImageBase, &ESE_INTERCEPT_sub_6FD0FE50, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FD0FE50_Original},
        {0x6FD0FE80 - D2GameImageBase, &ESE_INTERCEPT_sub_6FD0FE80, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FD0FE80_Original},
        {0x6FD10140 - D2GameImageBase, &ESE_INTERCEPT_sub_6FD10140, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FD10140_Original},
        {0x6FD10200 - D2GameImageBase, &ESE_INTERCEPT_sub_6FD10200, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FD10200_Original},
        {0x6FD10250 - D2GameImageBase, &ESE_INTERCEPT_sub_6FD10250, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FD10250_Original},
        {0x6FD10360 - D2GameImageBase, &ESE_INTERCEPT_sub_6FD10360, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FD10360_Original},
        {0x6FD10630 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_FindAuraTarget, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_FindAuraTarget_Original},
        {0x6FD106F0 - D2GameImageBase, &ESE_INTERCEPT_sub_6FD106F0, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FD106F0_Original},
        {0x6FD10790 - D2GameImageBase, &ESE_INTERCEPT_sub_6FD10790, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FD10790_Original},
        {0x6FD107E0 - D2GameImageBase, &ESE_INTERCEPT_sub_6FD107E0, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FD107E0_Original},
        {0x6FD107F0 - D2GameImageBase, &ESE_INTERCEPT_sub_6FD107F0, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FD107F0_Original},
        {0x6FD10880 - D2GameImageBase, &ESE_INTERCEPT_sub_6FD10880, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FD10880_Original},
        
        // SkillSor
        {0x6FD156F0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_DoInferno, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_DoInferno_Original},
        {0x6FD15940 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_StartInferno, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_StartInferno_Original},
        {0x6FD15AB0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt11_Inferno_ArcticBlast, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt11_Inferno_ArcticBlast_Original},
        {0x6FD15B40 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt12_Telekinesis_DragonFlight, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt12_Telekinesis_DragonFlight_Original},
        {0x6FD15CF0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt13_ThunderStorm, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt13_ThunderStorm_Original},
        {0x6FD15D50 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvSt14_Hydra, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvSt14_Hydra_Original},
        {0x6FD15E50 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_MissileInit_ChargedBolt, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_MissileInit_ChargedBolt_Original},
        {0x6FD15EB0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo017_ChargedBolt_BoltSentry, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo017_ChargedBolt_BoltSentry_Original},
        {0x6FD16040 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_CurseStateCallback_DefensiveBuff, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_CurseStateCallback_DefensiveBuff_Original},
        {0x6FD160A0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo018_DefensiveBuff, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo018_DefensiveBuff_Original},
        {0x6FD16270 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo019_Inferno_ArcticBlast, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo019_Inferno_ArcticBlast_Original},
        {0x6FD162D0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo020_StaticField, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo020_StaticField_Original},
        {0x6FD163E0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_AuraCallback_StaticField, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_AuraCallback_StaticField_Original},
        {0x6FD166A0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo021_Telekinesis, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo021_Telekinesis_Original},
        {0x6FD169A0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo022_NovaAttack, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo022_NovaAttack_Original},
        {0x6FD16A60 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo023_Blaze_EnergyShield_SpiderLay, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo023_Blaze_EnergyShield_SpiderLay_Original},
        {0x6FD16C00 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_CreateBlazeMissile, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_CreateBlazeMissile_Original},
        {0x6FD16D70 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo024_FireWall, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo024_FireWall_Original},
        {0x6FD17040 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo025_Enchant, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo025_Enchant_Original},
        {0x6FD17200 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo026_ChainLightning, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo026_ChainLightning_Original},
        {0x6FD172B0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo151_Unused, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo151_Unused_Original},
        {0x6FD17450 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo027_Teleport, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo027_Teleport_Original},
        {0x6FD174E0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo028_Meteor_Blizzard_Eruption_BaalTaunt_Catapult, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo028_Meteor_Blizzard_Eruption_BaalTaunt_Catapult_Original},
        {0x6FD17570 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo029_ThunderStorm, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo029_ThunderStorm_Original},
        {0x6FD17820 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_EventFunc24_EnergyShield, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_EventFunc24_EnergyShield_Original},
        {0x6FD17C30 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_SrvDo144_Hydra, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_SrvDo144_Hydra_Original},
        {0x6FD17F40 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_EventFunc01_ChillingArmor, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_EventFunc01_ChillingArmor_Original},
        {0x6FD180E0 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_EventFunc02_FrozenArmor, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_EventFunc02_FrozenArmor_Original},
        {0x6FD18200 - D2GameImageBase, &ESE_INTERCEPT_SKILLS_EventFunc03_ShiverArmor, PatchAction::FunctionReplaceOriginalByPatch, &SKILLS_EventFunc03_ShiverArmor_Original},
        
        // MissMode
        {0x6FC55CE0 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_UnitFindCallback_CanCollideWithMonster, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_UnitFindCallback_CanCollideWithMonster_Original},
        {0x6FC55D90 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_UnitFindCallback_CanCollideWithGoodAlignmentUnit, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_UnitFindCallback_CanCollideWithGoodAlignmentUnit_Original},
        {0x6FC55E60 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_UnitFindCallback_CanCollideWithPlayerOrMonster, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_UnitFindCallback_CanCollideWithPlayerOrMonster_Original},
        {0x6FC55F20 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_UnitFindCallback_CanMissileDestroy, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_UnitFindCallback_CanMissileDestroy_Original},
        {0x6FC55F80 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_FillDamageParams, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_FillDamageParams_Original},
        {0x6FC56290 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_RollDamageValue, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_RollDamageValue_Original},
        {0x6FC56480 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_GetDamageValue, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_GetDamageValue_Original},
        {0x6FC56730 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_ResetDamageParams, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_ResetDamageParams_Original},
        {0x6FC567E0 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_AddDamageValue, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_AddDamageValue_Original},
        {0x6FC568F0 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_CreatePoisonCloudHitSubmissiles, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_CreatePoisonCloudHitSubmissiles_Original},
        {0x6FC56AB0 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_CreateImmolationArrowHitSubmissiles, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_CreateImmolationArrowHitSubmissiles_Original},
        {0x6FC56D50 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_HandleMissileCollision, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_HandleMissileCollision_Original},
        {0x6FC56FA0 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_CreatePlagueJavelin_PoisonJavelin_PoisonTrapHitSubmissiles, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_CreatePlagueJavelin_PoisonJavelin_PoisonTrapHitSubmissiles_Original},
        {0x6FC570B0 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_SrvDo02_PlagueJavelin_PoisonJavelin_PoisonTrap, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_SrvDo02_PlagueJavelin_PoisonJavelin_PoisonTrap_Original},
        {0x6FC57140 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_SrvDo03_PoisonCloud_Blizzard_ThunderStorm_HandOfGod, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_SrvDo03_PoisonCloud_Blizzard_ThunderStorm_HandOfGod_Original},
        {0x6FC571D0 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_SrvDo05_FireWall_ImmolationFire_MeteorFire_MoltenBoulderFirePath, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_SrvDo05_FireWall_ImmolationFire_MeteorFire_MoltenBoulderFirePath_Original},
        {0x6FC573B0 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_SrvDo06_MoltenBoulder_FireWallMaker, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_SrvDo06_MoltenBoulder_FireWallMaker_Original},
        {0x6FC57510 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_SrvDo07_GuidedArrow_BoneSpirit, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_SrvDo07_GuidedArrow_BoneSpirit_Original},
        {0x6FC57640 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_SrvDo08_MonBlizzCenter, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_SrvDo08_MonBlizzCenter_Original},
        {0x6FC576F0 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_CreateMissileWithCollisionCheck, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_CreateMissileWithCollisionCheck_Original},
        {0x6FC57910 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_SrvDo09_BatLightningBolt, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_SrvDo09_BatLightningBolt_Original},
        {0x6FC57A40 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_SrvDo10_BlizzardCenter, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_SrvDo10_BlizzardCenter_Original},
        {0x6FC57B60 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_SrvDo11_FingerMageSpider, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_SrvDo11_FingerMageSpider_Original},
        {0x6FC57DA0 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_SrvDo12_DiabWallMaker, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_SrvDo12_DiabWallMaker_Original},
        {0x6FC57F00 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_SrvDo13_BoneWallMaker, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_SrvDo13_BoneWallMaker_Original},
        {0x6FC58140 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_SrvDo14_GrimWard, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_SrvDo14_GrimWard_Original},
        {0x6FC581F0 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_SrvDo15_FrozenOrb, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_SrvDo15_FrozenOrb_Original},
        {0x6FC58340 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_SrvDo16_FrozenOrbNova, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_SrvDo16_FrozenOrbNova_Original},
        {0x6FC58480 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_SrvDo17_CairnStones, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_SrvDo17_CairnStones_Original},
        {0x6FC585E0 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_SrvDo18_TowerChestSpawner, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_SrvDo18_TowerChestSpawner_Original},
        {0x6FC58860 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_SrvDo20_BladeCreeper, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_SrvDo20_BladeCreeper_Original},
        {0x6FC58940 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_SrvDo21_Distraction, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_SrvDo21_Distraction_Original},
        {0x6FC58B00 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_SrvDo22_LightningTrailingJavelin, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_SrvDo22_LightningTrailingJavelin_Original},
        {0x6FC58CC0 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_SrvDo23_24_SuccFireBall_FirestormMaker, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_SrvDo23_24_SuccFireBall_FirestormMaker_Original},
        {0x6FC58E10 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_SrvDo25_EruptionCenter, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_SrvDo25_EruptionCenter_Original},
        {0x6FC58F30 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_SrvDo26_Vines_PlagueVines, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_SrvDo26_Vines_PlagueVines_Original},
        {0x6FC59040 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_SrvDo27_Tornado, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_SrvDo27_Tornado_Original},
        {0x6FC591C0 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_SrvDo28_Volcano, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_SrvDo28_Volcano_Original},
        {0x6FC594B0 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_SrvDo29_RecyclerDelay, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_SrvDo29_RecyclerDelay_Original},
        {0x6FC596C0 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_SrvDo33_VineRecyclerDelay, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_SrvDo33_VineRecyclerDelay_Original},
        {0x6FC598D0 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_SrvDo30_RabiesPlague, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_SrvDo30_RabiesPlague_Original},
        {0x6FC59B90 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_SrvDo31_WakeOfDestructionMaker_BaalColdMaker, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_SrvDo31_WakeOfDestructionMaker_BaalColdMaker_Original},
        {0x6FC59CB0 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_SrvDo32_TigerFury, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_SrvDo32_TigerFury_Original},
        {0x6FC59D80 - D2GameImageBase, &ESE_INTERCEPT_MISSMODE_SrvDo34_BaalTauntControl, PatchAction::FunctionReplaceOriginalByPatch, &MISSMODE_SrvDo34_BaalTauntControl_Original},
        
        // MonsterUnique
        {0x6FC6AF70 - D2GameImageBase, &ESE_INTERCEPT_MONSTERUNIQUE_CalculatePercentage, PatchAction::FunctionReplaceOriginalByPatch, &MONSTERUNIQUE_CalculatePercentage_Original},
        {0x6FC6B030 - D2GameImageBase, &ESE_INTERCEPT_MONSTERUNIQUE_UMod16_Champion, PatchAction::FunctionReplaceOriginalByPatch, &MONSTERUNIQUE_UMod16_Champion_Original},
        {0x6FC6B210 - D2GameImageBase, &ESE_INTERCEPT_MONSTERUNIQUE_UMod36_Ghostly, PatchAction::FunctionReplaceOriginalByPatch, &MONSTERUNIQUE_UMod36_Ghostly_Original},
        {0x6FC6B4B0 - D2GameImageBase, &ESE_INTERCEPT_MONSTERUNIQUE_UMod39_Berserk, PatchAction::FunctionReplaceOriginalByPatch, &MONSTERUNIQUE_UMod39_Berserk_Original},
        {0x6FC6B610 - D2GameImageBase, &ESE_INTERCEPT_MONSTERUNIQUE_UMod8_Resistant, PatchAction::FunctionReplaceOriginalByPatch, &MONSTERUNIQUE_UMod8_Resistant_Original},
        {0x6FC6BA70 - D2GameImageBase, &ESE_INTERCEPT_MONSTERUNIQUE_UMod5_Strong, PatchAction::FunctionReplaceOriginalByPatch, &MONSTERUNIQUE_UMod5_Strong_Original},
        {0x6FC6BC10 - D2GameImageBase, &ESE_INTERCEPT_MONSTERUNIQUE_UMod9_FireEnchanted, PatchAction::FunctionReplaceOriginalByPatch, &MONSTERUNIQUE_UMod9_FireEnchanted_Original},
        {0x6FC6BDD0 - D2GameImageBase, &ESE_INTERCEPT_MONSTERUNIQUE_UMod17_LightningEnchanted, PatchAction::FunctionReplaceOriginalByPatch, &MONSTERUNIQUE_UMod17_LightningEnchanted_Original},
        {0x6FC6BF90 - D2GameImageBase, &ESE_INTERCEPT_MONSTERUNIQUE_UMod18_ColdEnchanted, PatchAction::FunctionReplaceOriginalByPatch, &MONSTERUNIQUE_UMod18_ColdEnchanted_Original},
        {0x6FC6C160 - D2GameImageBase, &ESE_INTERCEPT_MONSTERUNIQUE_UMod23_PoisonEnchanted, PatchAction::FunctionReplaceOriginalByPatch, &MONSTERUNIQUE_UMod23_PoisonEnchanted_Original},
        {0x6FC6C340 - D2GameImageBase, &ESE_INTERCEPT_MONSTERUNIQUE_UMod25_ManaSteal, PatchAction::FunctionReplaceOriginalByPatch, &MONSTERUNIQUE_UMod25_ManaSteal_Original},
        {0x6FC6C740 - D2GameImageBase, &ESE_INTERCEPT_MONSTERUNIQUE_CastCorpseExplode, PatchAction::FunctionReplaceOriginalByPatch, &MONSTERUNIQUE_CastCorpseExplode_Original},
        {0x6FC6C9E0 - D2GameImageBase, &ESE_INTERCEPT_MONSTERUNIQUE_CastCorpseExplode2, PatchAction::FunctionReplaceOriginalByPatch, &MONSTERUNIQUE_CastCorpseExplode2_Original},
        {0x6FC6CF10 - D2GameImageBase, &ESE_INTERCEPT_sub_6FC6CF10, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FC6CF10_Original},
        {0x6FC6CF90 - D2GameImageBase, &ESE_INTERCEPT_sub_6FC6CF90, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FC6CF90_Original},
        {0x6FC6D1C0 - D2GameImageBase, &ESE_INTERCEPT_MONSTERUNIQUE_ApplyElementalDamage, PatchAction::FunctionReplaceOriginalByPatch, &MONSTERUNIQUE_ApplyElementalDamage_Original},
        {0x6FC6E240 - D2GameImageBase, &ESE_INTERCEPT_sub_6FC6E240, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FC6E240_Original},
        {0x6FC6E410 - D2GameImageBase, &ESE_INTERCEPT_MONSTERUNIQUE_CastSuicideExplodeMissile, PatchAction::FunctionReplaceOriginalByPatch, &MONSTERUNIQUE_CastSuicideExplodeMissile_Original},
       
        // MonsterMode
        {0x6FC627B0 - D2GameImageBase, &ESE_INTERCEPT_sub_6FC627B0, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FC627B0_Original},
        {0x6FC62D90 - D2GameImageBase, &ESE_INTERCEPT_sub_6FC62D90, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FC62D90_Original},
        {0x6FC62DF0 - D2GameImageBase, &ESE_INTERCEPT_sub_6FC62DF0, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FC62DF0_Original},
        {0x6FC62E70 - D2GameImageBase, &ESE_INTERCEPT_D2GAME_MONSTER_ApplyCriticalDamage_6FC62E70, PatchAction::FunctionReplaceOriginalByPatch, &D2GAME_MONSTER_ApplyCriticalDamage_6FC62E70_Original},
        {0x6FC63440 - D2GameImageBase, &ESE_INTERCEPT_D2GAME_ApplyPeriodicStatDamage_6FC63440, PatchAction::FunctionReplaceOriginalByPatch, &D2GAME_ApplyPeriodicStatDamage_6FC63440_Original},
        {0x6FC63B30 - D2GameImageBase, &ESE_INTERCEPT_sub_6FC63B30, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FC63B30_Original},
        {0x6FC63FD0 - D2GameImageBase, &ESE_INTERCEPT_sub_6FC63FD0, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FC63FD0_Original},
        {0x6FC64090 - D2GameImageBase, &ESE_INTERCEPT_sub_6FC64090, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FC64090_Original},
        {0x6FC641D0 - D2GameImageBase, &ESE_INTERCEPT_sub_6FC641D0, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FC641D0_Original},
        {0x6FC64790 - D2GameImageBase, &ESE_INTERCEPT_sub_6FC64790, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FC64790_Original},
       
        // ObjEval
        {0x6FC745D0 - D2GameImageBase, &ESE_INTERCEPT_OBJEVAL_ApplyTrapObjectDamage, PatchAction::FunctionReplaceOriginalByPatch, &OBJEVAL_ApplyTrapObjectDamage_Original},
       
        // SUnitDmg
        {0x6FCBE2F0 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_SetHitClass, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_SetHitClass_Original},
        {0x6FCBE310 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_GetColdEffect, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_GetColdEffect_Original},
        {0x6FCBE360 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_RemoveFreezeState, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_RemoveFreezeState_Original},
        {0x6FCBE420 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_ApplyDamageBonuses, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_ApplyDamageBonuses_Original},
        {0x6FCBE7E0 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_FillDamageValues, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_FillDamageValues_Original},
        {0x6FCBF400 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_CheckMonType, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_CheckMonType_Original},
        {0x6FCBF450 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_RollDamageValueInRange, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_RollDamageValueInRange_Original},
        {0x6FCBF620 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_CalculateTotalDamage, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_CalculateTotalDamage_Original},
        {0x6FCBFB40 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_ApplyResistancesAndAbsorb, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_ApplyResistancesAndAbsorb_Original},
        {0x6FCBFE90 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_ExecuteEvents, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_ExecuteEvents_Original},
        {0x6FCC05D0 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_GetMonStatsTxtRecordFromUnit, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_GetMonStatsTxtRecordFromUnit_Original},
        {0x6FCC05F0 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_AddLeechedLife, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_AddLeechedLife_Original},
        {0x6FCC0660 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_AddLeechedMana, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_AddLeechedMana_Original},
        {0x6FCC06C0 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_ApplyPoisonDamage, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_ApplyPoisonDamage_Original},
        {0x6FCC0800 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_ApplyBurnDamage, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_ApplyBurnDamage_Original},
        {0x6FCC0940 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_ApplyColdState, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_ApplyColdState_Original},
        {0x6FCC0B90 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_RemoveShatterState, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_RemoveShatterState_Original},
        {0x6FCC0BE0 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_ApplyFreezeState, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_ApplyFreezeState_Original},
        {0x6FCC0E20 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_FreeAttackerCombatList, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_FreeAttackerCombatList_Original},
        {0x6FCC0E90 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_FreeAttackerDefenderCombatList, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_FreeAttackerDefenderCombatList_Original},
        {0x6FCC0F10 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_KillMonster, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_KillMonster_Original},
        {0x6FCC1260 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_ExecuteMissileDamage, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_ExecuteMissileDamage_Original},
        {0x6FCC1870 - D2GameImageBase, &ESE_INTERCEPT_sub_6FCC1870, PatchAction::FunctionReplaceOriginalByPatch, &sub_6FCC1870_Original},
        {0x6FCC1A50 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_GetHitClass, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_GetHitClass_Original},
        {0x6FCC1AC0 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_DrainItemDurability, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_DrainItemDurability_Original},
        {0x6FCC1D70 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_GetDamageFromUnits, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_GetDamageFromUnits_Original},
        {0x6FCC1DC0 - D2GameImageBase, &ESE_INTERCEPT_D2Game_10033, PatchAction::FunctionReplaceOriginalByPatch, &D2Game_10033_Original},
        {0x6FCC1E70 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_IsHitSuccessful, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_IsHitSuccessful_Original},
        {0x6FCC2300 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_GetResultFlags, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_GetResultFlags_Original},
        {0x6FCC2420 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_AllocCombat, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_AllocCombat_Original},
        {0x6FCC2530 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_ApplyBlockOrDodge, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_ApplyBlockOrDodge_Original},
        {0x6FCC2610 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_ApplyDodge, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_ApplyDodge_Original},
        {0x6FCC2850 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_GetWeaponBlock, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_GetWeaponBlock_Original},
        {0x6FCC2910 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_SetMissileDamageFlagsForNearbyUnits, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_SetMissileDamageFlagsForNearbyUnits_Original},
        {0x6FCC2BC0 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_RollDamage, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_RollDamage_Original},
        {0x6FCC2BF0 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_RollSuckBloodDamage, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_RollSuckBloodDamage_Original},
        {0x6FCC2C70 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_DistributeExperience, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_DistributeExperience_Original},
        {0x6FCC2EC0 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_ComputeExperienceGain, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_ComputeExperienceGain_Original},
        {0x6FCC3170 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_AddExperienceForPlayer, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_AddExperienceForPlayer_Original},
        {0x6FCC3200 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_PartyCallback_ComputePartyExperience, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_PartyCallback_ComputePartyExperience_Original},
        {0x6FCC3360 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_AddExperienceForHireling, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_AddExperienceForHireling_Original},
        {0x6FCC34A0 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_AddExperience, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_AddExperience_Original},
        {0x6FCC3510 - D2GameImageBase, &ESE_INTERCEPT_SUNITDMG_SetExperienceForTargetLevel, PatchAction::FunctionReplaceOriginalByPatch, &SUNITDMG_SetExperienceForTargetLevel_Original},
        { 0, 0, PatchAction::Ignore}, // Here because we need at least one element in the array
    };

    __declspec(dllexport) constexpr int __cdecl GetExtraPatchActionsCount() { return sizeof(extraPatchActions) / sizeof(ExtraPatchAction); }

    __declspec(dllexport) ExtraPatchAction* __cdecl GetExtraPatchAction(int index)
    {
        return &extraPatchActions[index];
    }
}

#include <type_traits>
static_assert(std::is_same<decltype(GetBaseOrdinal)*, GetIntegerFunctionType>::value, "Ensure calling convention doesn't change");
static_assert(std::is_same<decltype(GetLastOrdinal)*, GetIntegerFunctionType>::value, "Ensure calling convention doesn't change");
static_assert(std::is_same<decltype(GetPatchAction)*, GetPatchActionType>::value, "Ensure calling convention doesn't change");

static_assert(std::is_same<decltype(GetExtraPatchActionsCount)*, GetIntegerFunctionType>::value, "Ensure calling convention doesn't change");
static_assert(std::is_same<decltype(GetExtraPatchAction)*, GetExtraPatchActionType>::value, "Ensure calling convention doesn't change");
